name: kaeta_sandbox
description: "A new Flutter project for Kaeta! Prototype."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 状態管理
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # バックエンド & 同期
  supabase_flutter: ^2.6.0
  powersync: ^1.5.0

  # ローカルDB
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.21

  # データモデル & ユーティリティ
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^4.5.2

  path_provider: ^2.1.3
  path: ^1.9.0
  powersync_flutter_libs: ^0.4.14
  drift_sqlite_async: ^0.2.6
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  image_picker: ^1.1.2
  image_cropper: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # 最新版に統一

  # コード生成ツール群
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  drift_dev: ^2.16.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true